### ISSUE TITLE
Potential Bug: displaying negative value

### ISSUE THREAD

**Issue by XiaoyuZeng** [renkun-ken/formattable#118] opened 2019-07-29 14:31 UTC
Hi @renkun-ken

Thanks for your contribution to the amazing tool to display data table. However, I found that when displaying negative value, the minus sign is always being displayed behind the number (see attached figure if it is uploaded properly). My colleagues complained about this, so I'm wondering whether it's a serious problem. Do you think this problem is possible to be improved?

![image](https://user-images.githubusercontent.com/38243112/62056276-e5425180-b24f-11e9-89c2-3c8a8c879089.png)

**Comment by renkun-ken** [comment] 2019-07-29 16:03
It's caused by the right-alignment of css `direction: rtl`. It's known but apparently not desired. I'll fix this when I find a better way to represent the HTML element without having to rely on `direction: rtl`.

**Comment by renkun-ken** [comment] 2019-07-30 20:30
I believe this has been resolved by 4de31bb313e398059bc682ef0d927df895dff796 thanks to the CSS property `unicode-bidi` introduced at <https://stackoverflow.com/a/37143762/2906900>. `unicode-bidi: plaintext` seems to make the signed numbers look right while the right-alignment is preserved. 

For more details, see <https://www.w3schools.com/cssref/pr_text_unicode-bidi.asp>.

**Closed by renkun-ken** 2019-07-30 20:30 UTC
